# for old k8s cluster:
# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx-depl-2
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      conf: password
  template:
    metadata:
      namespace: default
      labels:
        app: nginx
        conf: password
    spec:
      volumes:
      - name: pod-config-1
        configMap:
          name: config-1
          items:
            - key: password
              path: index.html
      containers:
      - image: nginx:1.13
        imagePullPolicy: IfNotPresent
        name: nginx-pod-2
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/www/html
          name: pod-config-1
          readOnly: true