# for old k8s cluster:
# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx-depl-3
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      backend: go
  template:
    metadata:
      namespace: default
      labels:
        app: nginx
        backend: go
    spec:
      containers:
      - image: nginx:1.13
        imagePullPolicy: IfNotPresent
        name: nginx-pod-3
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "200m"
      - image: evelynocean/hello:0.1
        imagePullPolicy: IfNotPresent
        name: evelyn-hello
        ports:
          - containerPort: 1031
            protocol: TCP
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "200m"