# for old k8s cluster:
# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx-depl-1
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      secr: account
  template:
    metadata:
      namespace: default
      labels:
        app: nginx
        secr: account
    spec:
      volumes:
      - name: pod-secret-1
        secret:
          secretName: secret-1
          items:
          - key: account
            path: index.html
      containers:
      - image: nginx:1.13
        imagePullPolicy: IfNotPresent
        name: nginx-pod-1
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/www/html
          name: pod-secret-1