apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    conf: password
  name: nginx-pod-2
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-pod
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/www/html
      name: pod-config-1
      readOnly: true
  volumes:
  - name: pod-config-1
    configMap:
      name: config-1
      items:
        - key: password
          path: password
