apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    backend: go
  name: nginx-pod-3
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-pod
    ports:
      - containerPort: 3000
        protocol: TCP
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "120Mi"
        cpu: "200m"
  - image: evelynocean/hello:0.1
    imagePullPolicy: Always
    name: evelyn-hello
    ports:
      - containerPort: 1031
        protocol: TCP
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "120Mi"
        cpu: "200m"