apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: default
spec:
  selector:
    app: nginx
    secr: account
    conf: password
    backend: go
  ports:
  - port: 80
    # name: http1
    protocol: TCP
    # nodePort: 80
  # - port: 2000
  #   name: http2
  #   protocol: TCP
  #   nodePort: 30002
  # - port: 3000
  #   name: http3
  #   protocol: TCP
  #   nodePort: 30003
  # - port: 1031
  #   name: go
  #   protocol: TCP
  #   nodePort: 30004
  sessionAffinity: None
  type: NodePort