apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # labels:
  #   app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      # name: nginx-pod-1
      # namespace: default
      labels:
        app: nginx-pod
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-container
        ports:
        - containerPort: 80